### PR TITLE
Added missing position property, Legend plugin

### PR DESCRIPTION
**Pull request by stephanstapel**

### CODE REVIEW

**Comment by stephanstapel** [comment]
sorry for asking this after issuing the pull request: I saw that precision, position and stepsize are members of CartesianLinearTick whereas I added them to Tick class. Wondering which approach is correct here?

**Comment by mattosaurus** [comment]
Hi, is it not possible to do all of this using the PluginDynamic property rather than adding these additional properties?

I don't really want to add the onclick method to the code as that's something that should be defined by the user rather than in the code base.

**Comment by stephanstapel** [comment]
Hi,
of course I can add this as a plugin dynamic. I thought sharing it with other users as a dedicated plugin could be nice for everybody!

**Comment by stephanstapel** [comment]
updated readme!

**Comment by stephanstapel** [comment]
Hi @mattosaurus ,
I just wanted to ask if there is anything I could to do get this pull request accepted. At least the legend plugin is quite nice for a lot of people I think since it allows you to invert the legend click behaviour (which is a bit counter-intuitive in standard ChartJS)

**Review by mattosaurus — APPROVED** [review]

**Comment by mattosaurus** [comment]
Sorry, I lost track of this. I've published a new v3.10.1 version of this now.

**Pull request merged**
